### ISSUE TITLE
Error in loading component

### ISSUE THREAD

**Issue by vaishali-ghayal** [greghub/vue-funnel-graph-js#1]
ERROR in ./node_modules/vue-funnel-graph-js/dist/vue-funnel-graph.esm.js
Module not found: Error: Can't resolve 'sass-loader' in '/src'
 @ ./node_modules/vue-funnel-graph-js/dist/vue-funnel-graph.esm.js 6:0-44
 @ ./src/main.js
 @ multi babel-polyfill ./src/main.js webpack-hot-middleware/client
ERROR in ./node_modules/vue-funnel-graph-js/dist/vue-funnel-graph.esm.js
Module not found: Error: Can't resolve 'sass-loader' in '/src'
 @ ./node_modules/vue-funnel-graph-js/dist/vue-funnel-graph.esm.js 7:0-45
 @ ./src/main.js
 @ multi babel-polyfill ./src/main.js webpack-hot-middleware/client

**Comment by greghub** [comment]
Hi, @vaishali-ghayal, thank you for raising the issue. Please install `node-sass` and `sass-loader` or update the `vue-funnel-graph-js`, I fixed this issue in version 0.1.4
