### ISSUE TITLE
subLabelValue

### ISSUE THREAD

**Issue by chrisbell08** [greghub/vue-funnel-graph-js#12]
Hey 

I'm trying to set subLabelValue to 'raw' based on the funnel graph js docs but it doesn't seem to work, 

Can this be added in?

**Comment by greghub** [comment]
Hi @chrisbell08 thank you for opening the issue. The support for subLabelValue is now added in verions `0.1.7`. Add `:sub-label-value` prop to the `vue-funnel-graph element.
