### ISSUE TITLE
Initial direction value

### ISSUE THREAD

**Issue by felipebiox** [greghub/vue-funnel-graph-js#3]
Hello,

I'm loving this component, but I've been struggling for quite a while trying to make the vertical direction work correctly. Maybe it's something I'm missing.

In my project, the props **direction="vertical"** is not working as a initial state

Changing the props later with external events works, but I wanted the graph to render vertically without the need of a button to set it up to vertical.

Setting direction vertical as a default prop makes the labels vertical, but not the graph

**Comment by greghub** [comment]
Thank you @felipebiox 
Issue fixed in version `0.1.6`
