### ISSUE TITLE
Direction doesn't change

### ISSUE THREAD

**Issue by dhertzb** [greghub/vue-funnel-graph-js#4]
Chart aways display in horizontal direction even when option is setted to vertical.
----------------------------------------------------------------------------------------------------------

Code:
<template>
            <div class="container-fluid d-flex align-items-center">
                <vue-funnel-graph :width="width" :height="height" :labels="labels"
                :values="values" :colors="colors" :sub-labels="subLabels" :direction="direction"
                :gradient-direction="gradientDirection"
                :animated="true" :display-percentage="true"
                ></vue-funnel-graph>
            </div>
</template>
<script>
    import { VueFunnelGraph } from 'vue-funnel-graph-js';

    export default{
        components: {
            VueFunnelGraph
        },
        data() {
          return {
              labels: ['Ativos', 'Prospects', 'Inativos'],
              subLabels: ['Direct', 'Social Media', 'Ads'],
              values: [
          // with the given Labels and SubLabels here's what the values represent:
          // 
          // Direct, Social, Ads  
          //    |      |     |  
          //    v      v     v
              [3000, 2500, 6500], // Segments of "Impressions" from top to bottom
              [3000, 1700, 1000], // Segments of "Add To Cart"
              [600,  200,  130]   // Segments of "Buy"
              ],
              colors: [
              ['#FFB178', '#FF3C8E'], // color set for "Impressions" segment
              ['#A0BBFF', '#EC77FF'], // color set for "Add To Cart" segment
              ['#A0F9FF', '#7795FF']  // color set for "Buy" segment
              ],
              direction: 'vertical', 
              gradientDirection: 'vertical',
              height: 300,
              width: 250
          };
      }
  }
</script>

----------------------------------------------------------------------------------------------------------

Other question: 

There is a way to make the chart responsive?

----------------------------------------------------------------------------------------------------------
Great job, its the most aestetic chart for sure, thanks

**Comment by oliverbl4** [comment]
Hi @dhertzb,
I'm afraid that it works with a watcher so it loads by default in horizontal. If you want to change it you should do a button or a function that loads after the graph has been loaded.

**Comment by dhertzb** [comment]
`      methods:{
        makeVertical() {
          this.direction = 'vertical';
          this.height = 500;
          this.width = 400;
        },
    },
      created() {
       this.makeVertical();
    }`
any idea?
Even using this method it remains horizontal

**Comment by oliverbl4** [comment]
I’m using nuxt with SSR and I’m loading this from the client, so I fixed with the fastest way but not the best. You can do:
created() {
setTimeout(this.makeVertical, 1000);
} 
You’ll see that now it changes to vertical mode. If it doesn’t you may need to set more time.
A proper way would be with a method after this module has loaded 🤷‍♂️
Hope I could help you!

**Comment by dhertzb** [comment]
I think I've fixed it, in the vue component there is the function beforeMount that is missing some properties, I just added  'direction: this.direction' with a npm link to test and its working like a charm
